
version: "3"

services:

  fmp-pmc:
    image: nginx:1.22.0
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /fmp/fmp-pmc/conf.d:/etc/nginx/conf.d
      - /fmp/fmp-pmc/www:/www
      - /fmp/fmp-pmc/ssl:/ssl
