
version: "3"

services:

  fmp-daemon:
    image: xtechcloud/fmp-daemon:v1.0.0
    restart: always
    ports:
      - "16166:16166"
      - "28000-28099:28000-28099"
      - "29000-29099:29000-29099"
    volumes:
      - /fmp/fmp-daemon/apps:/app/apps
      - /fmp/fmp-daemon/cers:/app/cers
