
version: "3"

services:

  mysql:
    image: mysql:8.0.26
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /nas/data/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mysql@XTC"

  mongo:
    image: mongo:5.0.9
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /nas/data/mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "mongo@XTC"

  redis:
    image: redis:7.0.4
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /nas/data/redis/data:/data

  minio:
    image: minio/minio:RELEASE.2022-07-30T05-21-40Z
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /nas/file/minio/data:/data
    environment:
      MINIO_ROOT_USER: "3KJLIOSFODNN0EXAMPO0"
      MINIO_ROOT_PASSWORD: "vJalrXUtnFEMI/I5MDENG/bPxRfmCYEXAMPLEHEY"
    command: server /data --console-address ":9001"
