
version: "3"

services:

  mysql:
    image: mysql:8.0.26
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /fmp/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mysql@XTC"
    networks:
      vpc:
        ipv4_address: 10.1.2.11

  mongo:
    image: mongo:5.0.9
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /fmp/mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "mongo@XTC"
    networks:
      vpc:
        ipv4_address: 10.1.2.21

  redis:
    image: redis:7.0.4
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /fmp/redis/data:/data
    networks:
      vpc:
        ipv4_address: 10.1.2.31

  minio:
    image: minio/minio:RELEASE.2022-07-30T05-21-40Z
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /fmp/minio/data:/data
    environment:
      MINIO_ROOT_USER: "3KJLIOSFODNN0EXAMPO0"
      MINIO_ROOT_PASSWORD: "vJalrXUtnFEMI/I5MDENG/bPxRfmCYEXAMPLEHEY"
    command: server /data --console-address ":9001"
    networks:
      vpc:
        ipv4_address: 10.1.2.41

networks:
  vpc:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.0.0/16
